site_name: brain-os
site_description: Construindo um sistema operacional do zero
docs_dir: .

theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: purple
  font:
    code: JetBrains Mono

nav:
  - Início: index.md
  - IDT — Interrupções: idt.md
  - PIC — Hardware Interrupts: pic.md
  - Teclado — IRQ1 e Scancodes: keyboard.md
